### ISSUE TITLE
Error 90001

### ISSUE THREAD

**Issue by Rockieh** [JustinCase144/FootSwitchPtt#1]
Ei toimi 🥺

**Comment by JustinCase144** [comment]
Tarttis lisätietoi. 

Postaakko backlog.log dmesg directx.log ja pieret ripalia. 

Sit viel: 

1. Mikä käyttis
2. Kuka sä oot
3. Mitä mä teen täällä
4. Ookkonä kommunisti
5. Mikset oo
6. Kengänkoko
7. Koska kävit viimmeksi paskalla
8. Onko Michael Boltonilla komia takatukka
9. Maista sibs uudet maut
10. Hernekeitto
11. Viina
12. Teline
13. Johannes

**Comment by Rockieh** [comment]
1. MAcFatOsama
2. reijo
3. bailaat
4. yes
5. noq
6. 69 nice
7. huomenna
8. on
9. verinice
10. 2purkkia
11. no
12. 6kpl kiitos
13. Jeesus ja panssarivaun
[Backlog.log](htt
[Directx.log](https://github.com/JustinCase144/FootSwitchPtt/files/9174634/Directx.log)
ps://github.com/JustinCase144/FootSwitchPtt/files/9174632/Backlog.log)
u

**Comment by Rockieh** [comment]
[Backlog.log](https://github.com/JustinCase144/FootSwitchPtt/files/9174636/Backlog.log)

**Comment by Rockieh** [comment]
### homma **kusee** _kunnolla_

**Comment by JustinCase144** [comment]
Iha vitun 5/5 ongelma ratkaistu, bugit korjattu, maailmanrauha saavutettu, kukaan ei näe enää nälkää ja vitun threadi CLOSED!

**Comment by Rockieh** [comment]
![ChDazNM](https://user-images.githubusercontent.com/109862393/180622700-41ddd7f1-6bcc-48aa-853e-945ebcd728f0.jpg)


Kiitos<3

**Comment by Rockieh** [comment]
EI SE KIINNI OLE

- 

- [x] @ #`asdadsasdsadasdasd`

**Comment by JustinCase144** [comment]
> EI SE KIINNI OLE
> 
> * [x]  @ #`asdadsasdsadasdasd`

Ripalipimpula saatana

**Comment by JustinCase144** [comment]
sdfgfdg
